In [1]:
import pandas as pd

In [2]:
data_test = pd.read_csv("./Benchmark_dataset/HeldOut50/Test_0_0.tsv",delimiter='\t',header=None)

In [3]:
data_test

           0       1  2
0       6810    9342  1
1       2074    4170  0
2     221656  730291  0
3      54623   79812  0
4        351    2242  1
...      ...     ... ..
6825  284013  286749  0
6826    5355    6657  0
6827     239    3632  0
6828    2074    8335  1
6829    2115   63971  0

[6830 rows x 3 columns]

In [4]:
data_train = pd.read_csv("./Benchmark_dataset/HeldOut50/Train_0_0.tsv",delimiter='\t',header=None)

In [5]:
data_train

           0       1  2
0       8812  165140  1
1       5581   93953  0
2      56165  284293  0
3       1788   10919  1
4        999   54894  1
...      ...     ... ..
99995   3172   10987  1
99996  10107   58478  0
99997  27185   55180  0
99998   1674    6047  1
99999  23270   93979  0

[100000 rows x 3 columns]

In [9]:
train_prot = set(data_train[0]).union(set((data_train[1])))

In [10]:
train_prot

{1,
 2,
 9,
 10,
 12,
 13,
 14,
 15,
 16,
 18,
 19,
 20,
 22,
 23,
 131096,
 27,
 28,
 29,
 31,
 32,
 33,
 34,
 35,
 37,
 38,
 39,
 40,
 41,
 43,
 131118,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 56,
 58,
 59,
 70,
 71,
 72,
 81,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 98,
 100,
 101,
 102,
 105,
 131177,
 107,
 108,
 109,
 111,
 112,
 113,
 114,
 116,
 118,
 119,
 120,
 123,
 124,
 125,
 126,
 127,
 128,
 132,
 135,
 136,
 140,
 141,
 142,
 143,
 146,
 147,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 173,
 175,
 176,
 178,
 181,
 182,
 183,
 185,
 189,
 190,
 191,
 196,
 197,
 199,
 202,
 203,
 204,
 205,
 207,
 208,
 210,
 211,
 212,
 213,
 215,
 216,
 217,
 218,
 220,
 221,
 223,
 225,
 229,
 230,
 231,
 238,
 240,
 241,
 242,
 247,
 248,
 249,
 250,
 251,
 257,
 258,
 259,
 262,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 196883,
 276,
 277,
 278,
 275,
 279,
 280,
 284,
 285,
 286,
 287,
 288,
 290,
 291,
 292,
 293,
 131368,
 301,
 302,
 131375,
 131377,
 307,
 309,
 310,
 311,
 312,
 316,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 332,
 333,
 131405,
 335,
 336,
 337,
 338,
 339,
 131408,
 341,
 343,
 344,
 345,
 346,
 347,
 196951,
 350,
 354,
 355,
 356,
 357,
 358,
 360,
 361,
 362,
 363,
 364,
 366,
 367,
 368,
 373,
 374,
 375,
 377,
 378,
 131450,
 381,
 382,
 383,
 196993,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 131474,
 406,
 410,
 411,
 412,
 197021,
 414,
 415,
 417,
 419,
 427,
 429,
 430,
 432,
 433,
 435,
 438,
 439,
 65975,
 65977,
 440,
 443,
 65979,
 445,
 65982,
 65983,
 65980,
 65985,
 65986,
 65987,
 65988,
 65989,
 65990,
 65991,
 65992,
 65993,
 460,
 462,
 463,
 65999,
 66000,
 66002,
 466,
 468,
 66005,
 131540,
 471,
 472,
 66008,
 474,
 475,
 476,
 477,
 479,
 480,
 481,
 482,
 483,
 729540,
 488,
 489,
 491,
 492,
 493,
 495,
 496,
 498,
 66035,
 66036,
 66037,
 501,
 100532726,
 131578,
 100532731,
 509,
 131583,
 513,
 515,
 516,
 517,
 518,
 522,
 523,
 197131,
 525,
 526,
 527,
 131601,
 529,
 533,
 534,
 535,
 537,
 538,
 539,
 540,
 545,
 546,
 547,
 549,
 550,
 551,
 552,
 553,
 554,
 558,
 566,
 567,
 570,
 571,
 572,
 573,
 574,
 575,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 585,
 586,
 587,
 590,
 594,
 596,
 597,
 131669,
 599,
 602,
 604,
 605,
 607,
 608,
 610,
 611,
 613,
 617,
 622,
 623,
 627,
 629,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 648,
 649,
 650,
 651,
 652,
 197258,
 654,
 197259,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 675,
 676,
 678,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 694,
 695,
 699,
 701,
 705,
 706,
 710,
 713,
 714,
 197322,
 717,
 718,
 719,
 720,
 721,
 722,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 197335,
 197342,
 735,
 734,
 738,
 740,
 741,
 744,
 746,
 747,
 197358,
 752,
 753,
 754,
 757,
 758,
 131831,
 759,
 761,
 197370,
 762,
 765,
 766,
 770,
 771,
 773,
 774,
 775,
 777,
 778,
 779,
 780,
 781,
 782,
 784,
 786,
 788,
 790,
 793,
 794,
 795,
 796,
 131870,
 799,
 800,
 801,
 197407,
 131873,
 805,
 808,
 810,
 811,
 813,
 814,
 815,
 816,
 817,
 131890,
 819,
 818,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 830,
 831,
 832,
 833,
 835,
 836,
 837,
 838,
 839,
 840,
 842,
 843,
 844,
 845,
 846,
 847,
 131920,
 857,
 859,
 861,
 862,
 864,
 865,
 866,
 867,
 868,
 869,
 873,
 881,
 100533105,
 883,
 100533106,
 885,
 886,
 887,
 889,
 890,
 891,
 131965,
 894,
 896,
 898,
 899,
 900,
 902,
 904,
 905,
 908,
 910,
 912,
 913,
 914,
 915,
 916,
 917,
 920,
 921,
 922,
 924,
 925,
 926,
 928,
 929,
 930,
 931,
 932,
 933,
 132001,
 940,
 942,
 943,
 944,
 945,
 132014,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 100533177,
 100533178,
 958,
 959,
 960,
 961,
 962,
 963,
 100533181,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 973,
 975,
 976,
 977,
 983,
 984,
 987,
 988,
 989,
 990,
 991,
 993,
 994,
 995,
 997,
 998,
 999,
 1000,
 1003,
 1004,
 1006,
 1007,
 1008,
 1010,
 1012,
 1013,
 1014,
 1016,
 1017,
 1018,
 1019,
 1020,
 1021,
 1022,
 1024,
 1025,
 1026,
 1027,
 1028,
 1029,
 1030,
 1031,
 1033,
 1036,
 1038,
 1039,
 132112,
 1041,
 1040,
 1043,
 1044,
 1045,
 1047,
 1048,
 394263,
 1050,
 1051,
 1052,
 1053,
 1054,
 1056,
 1058,
 1060,
 1062,
 1063,
 1066,
 1068,
 132141,
 1070,
 1071,
 1072,
 1073,
 1075,
 1080,
 1081,
 1084,
 1087,
 132160,
 1089,
 1102,
 1104,
 1105,
 1106,
 1107,
 1108,
 1111,
 1112,
 1113,
 1114,
 1117,
 1118,
 1119,
 1120,
 1121,
 1123,
 1124,
 1128,
 1129,
 1130,
 1131,
 1132,
 1133,
 1134,
 1135,
 1136,
 1137,
 132203,
 1139,
 1140,
 1141,
 1142,
 1138,
 1144,
 1143,
 1146,
 1147,
 1145,
 1149,
 1152,
 1153,
 1154,
 132228,
 1158,
 1159,
 1160,
 1161,
 1164,
 132243,
 1173,
 1174,
 1175,
 1178,
 1179,
 1180,
 1181,
 1182,
 1183,
 1184,
 1185,
 1186,
 1187,
 1188,
 1191,
 1192,
 1195,
 1196,
 1200,
 1201,
 1203,
 1207,
 1209,
 1212,
 1213,
 1215,
 132299,
 1233,
 1234,
 1235,
 1236,
 1237,
 1238,
 1241,
 100533467,
 1244,
 132320,
 132321,
 1258,
 1259,
 1260,
 1261,
 1262,
 1263,
 1264,
 1265,
 1266,
 1267,
 1268,
 1269,
 1270,
 1271,
 1272,
 100533496,
 1277,
 1278,
 1280,
 1281,
 1282,
 1285,
 1286,
 1287,
 1288,
 1289,
 1290,
 1292,
 1294,
 1295,
 1298,
 1299,
 1300,
 1301,
 1302,
 1303,
 1305,
 1306,
 1307,
 1308,
 1310,
 1311,
 1312,
 1314,
 1315,
 1316,
 1317,
 1318,
 1325,
 1326,
 1329,
 1337,
 1340,
 1346,
 1347,
 1349,
 1351,
 1352,
 1353,
 1355,
 1356,
 1357,
 1358,
 1360,
 1361,
 1362,
 1363,
 1364,
 1365,
 1366,
 1368,
 1369,
 1370,
 1371,
 1373,
 1374,
 1375,
 1376,
 1378,
 1381,
 1382,
 1384,
 1386,
 1388,
 1389,
 1390,
 1392,
 1393,
 1394,
 1397,
 1398,
 1400,
 1401,
 1404,
 1406,
 1407,
 1408,
 1409,
 1410,
 1411,
 1412,
 1413,
 1415,
 1417,
 1418,
 1420,
 1421,
 1427,
 1428,
 1429,
 1431,
 1432,
 1435,
 1436,
 1437,
 1438,
 1439,
 1440,
 1441,
 1442,
 1443,
 1445,
 1446,
 1447,
 1448,
 1452,
 1453,
 1454,
 1456,
 1457,
 1459,
 1460,
 1462,
 1463,
 1464,
 1465,
 1466,
 1469,
 1471,
 1474,
 1475,
 1477,
 1478,
 1479,
 1482,
 1485,
 1486,
 1487,
 1488,
 1489,
 1490,
 1491,
 1493,
 1495,
 1496,
 1503,
 1504,
 1506,
 1509,
 1510,
 1511,
 1512,
 1513,
 1514,
 1515,
 1520,
 1521,
 1522,
 1523,
 1524,
 1525,
 1528,
 1534,
 1536,
 1538,
 1539,
 1540,
 132612,
 1543,
 1544,
 1545,
 1548,
 1549,
 1551,
 132625,
 1555,
 1557,
 1558,
 1562,
 1564,
 1565,
 1571,
 ...}

In [11]:
test_prot = set(data_test[0]).union(set((data_test[1])))

In [12]:
train_prot.intersection(test_prot)

set()